### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jambo199** [mov-cli/mov-cli-test#1]
![Screenshot_20240418-100600.png](https://github.com/THEGOLDENPRO/mov-cli-test/assets/109238072/6f85a6d7-4721-4905-9280-2ba8973aa86d)

**Comment by THEGOLDENPRO** [comment]
Despite that saying error, it most likely just isn't available on the provider hence no results were returned. Run your command with `--debug` to confirm and send the output here.

**Comment by THEGOLDENPRO** [comment]
wait, nevermind you are using the test scraper. The test scraper doesn't scrape for shows and films and I think ananas has already explained that on the discord.

**Comment by ananasmoe** [comment]
> I think ananas has already explained that on the discord.

I have
